# Generated by Django 3.1.5 on 2021-02-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_menus', '0002_auto_20210224_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='slug',
        ),
    ]
