# Generated by Django 3.1.5 on 2021-01-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LisgreyWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
