# Generated by Django 3.1.5 on 2021-02-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LisgreyWebApp', '0005_auto_20210224_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='line_total',
        ),
    ]
