# Generated by Django 3.1.5 on 2021-02-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LisgreyWebApp', '0006_remove_basketitem_line_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeawayorder',
            name='total',
        ),
    ]
