# Generated by Django 3.1.5 on 2021-02-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LisgreyWebApp', '0007_remove_takeawayorder_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
