"""
Django settings for LisgreyWebApp_FYP project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import socket

from django.contrib import messages

import docker_config
from pathlib import Path
from django.contrib.auth import login

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = docker_config.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = docker_config.DEPLOY_SECURE

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'LisgreyWebApp',
    'reservations',
    'takeaway',
    'food_menus',
    'crispy_forms',
    'bootstrap4',
    'corsheaders',
    'django_email_verification',  # you have to add this
    'pwa',
    'contact',
    'staff',
    'leaflet'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

ROOT_URLCONF = 'LisgreyWebApp_FYP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LisgreyWebApp_FYP.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'lisgrey_database',
        'USER': 'postgres',
        'PASSWORD': docker_config.PRODUCTION_PASSWORD,
        'HOST': '127.0.0.1',
        'PORT': '25432'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_FAIL_SILENTLY = not DEBUG

BOOTSTRAP4 = {
    'include_jquery': True,
}

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'  # new

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

TIME_INPUT_FORMATS = [
    '%H:%M %p'
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# Add this line to access static files on templates
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/"),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

if socket.gethostname() == "acer":  # if development on local machine
    DATABASES["default"]["HOST"] = "localhost"  # connect to local database on port 25432
    DATABASES["default"]["PORT"] = 25432
    DATABASES["default"]["PASSWORD"] = 'password'
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_PAGE_DOMAIN = 'http://localhost:8000'

else:  # if production
    DATABASES["default"]["HOST"] = "lisgrey-psql"  # connect to database container on droplet on port 5432
    DATABASES["default"]["PORT"] = 5432
    DATABASES["default"]["PASSWORD"] = docker_config.PRODUCTION_PASSWORD
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PAGE_DOMAIN = 'www.lisgreyhouse.com'

# Set DEPLOY_SECURE to True only for LIVE deployment
if docker_config.DEPLOY_SECURE:  # if config.py DEPLOY_SECURE = True
    DEBUG = False  # Turn Debug mode off
    TEMPLATES[0]["OPTIONS"]["debug"] = False
    ALLOWED_HOSTS = ['.lisgreyhouse.com', 'localhost', '138.68.130.143', '127.0.0.1', '192.168.1.145']  # Hosts allowed
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
else:
    DEBUG = True
    TEMPLATES[0]["OPTIONS"]["debug"] = True
    ALLOWED_HOSTS = ['*', ]
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False

# Email backend
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = docker_config.EMAIL
EMAIL_HOST_PASSWORD = docker_config.PASSWORD
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = docker_config.EMAIL


# Email Verification module
def verified(user):
    user.is_active = True


EMAIL_FROM_ADDRESS = docker_config.EMAIL
EMAIL_MAIL_SUBJECT = 'Confirm registration'
EMAIL_MAIL_HTML = 'email_body.html'
EMAIL_MAIL_PLAIN = 'email_body.txt'
EMAIL_TOKEN_LIFE = 60 * 60
EMAIL_PAGE_TEMPLATE = 'account_confirmation.html'
EMAIL_VERIFIED_CALLBACK = verified

AUTH_USER_MODEL = 'LisgreyWebApp.UserProfile'

# PWA Settings
PWA_APP_NAME = 'Lisgrey House'
PWA_APP_DESCRIPTION = "Web Application"
PWA_APP_THEME_COLOR = '#39606F'
PWA_APP_BACKGROUND_COLOR = '#39606F'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/images/icons/android-chrome-192x192.png',
        'sizes': '192x192'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/images/icons/apple-touch-icon.png',
        'sizes': '152x1524'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/icons/android-chrome-512x512.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js', 'serviceworker.js')

# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

#
# SESSION_SAVE_EVERY_REQUEST = True

MESSAGE_TAGS = {
    messages.ERROR: 'alert-danger',
    messages.SUCCESS: 'alert-success'
}
